import assert from "node:assert/strict";
import test from "node:test";

test("defines the private Caféhaus landing page", async () => {
  const fs = await import("node:fs/promises");
  const page = await fs.readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const layout = await fs.readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");
  assert.match(layout, /Caféhaus After Dark/);
  assert.match(page, /Invitation only/);
  assert.match(page, /Already invited/);
  assert.match(page, /original link/);
});

test("ships the real guest and host controls", async () => {
  const fs = await import("node:fs/promises");
  const guest = await fs.readFile(new URL("../app/components/GuestExperience.tsx", import.meta.url), "utf8");
  const host = await fs.readFile(new URL("../app/components/AdminExperience.tsx", import.meta.url), "utf8");
  const invitationApi = await fs.readFile(new URL("../app/api/invitations/token/[token]/route.ts", import.meta.url), "utf8");
  const rescindApi = await fs.readFile(new URL("../app/api/_invitations.ts", import.meta.url), "utf8");
  const orderApi = await fs.readFile(new URL("../app/api/orders/route.ts", import.meta.url), "utf8");
  const schema = await fs.readFile(new URL("../db/schema.ts", import.meta.url), "utf8");
  assert.match(guest, /Tonight’s/);
  assert.match(guest, /Place order/);
  assert.match(guest, /Global order line/);
  assert.match(guest, /RSVP for the evening/);
  assert.match(guest, /Changed your mind/);
  assert.match(guest, /Order alerts/);
  assert.match(guest, /recipe allergens/i);
  assert.match(guest, /cross-contact is possible/i);
  assert.match(guest, /Open in Maps/);
  assert.match(guest, /Add to calendar/);
  assert.match(guest, /Coffee passport/);
  assert.match(guest, /coffees served tonight/);
  assert.match(guest, /Attached to this invitation/);
  assert.match(guest, /navigator\.share/);
  assert.match(guest, /The room at the night before the day itself/);
  assert.match(guest, />Copy link</);
  assert.doesNotMatch(guest, />Invitation & RSVP</);
  assert.doesNotMatch(guest, /fresh share link/i);
  assert.doesNotMatch(guest, /Add to Home Screen/);
  assert.match(guest, /Awaiting reply/);
  assert.match(guest, /useState<RsvpResponse \| null>/);
  assert.match(guest, /Remove guest/);
  assert.match(guest, /maxLength=\{16\}/);
  assert.match(host, /Start making/);
  assert.match(host, /Ready on tray/);
  assert.match(host, /Service control/);
  assert.match(host, /Mise en place/);
  assert.match(host, /Exact recipe/);
  assert.match(host, /Timer due/);
  assert.match(host, /Change number/);
  assert.match(host, /Auto-archives/);
  assert.match(host, /Invitation manager/);
  assert.match(host, /Declined/);
  assert.match(host, /parentGuestName/);
  assert.match(host, /\+1 token/);
  assert.match(host, /Copy link/);
  assert.doesNotMatch(host, />New link</);
  assert.match(host, /maxLength=\{16\}/);
  assert.match(invitationApi, /normalizeFirstName/);
  assert.match(invitationApi, /status: "sent"/);
  assert.doesNotMatch(invitationApi, /rsvpResponse: "yes"/);
  assert.match(rescindApi, /token_balance = 0/);
  assert.match(rescindApi, /NOT EXISTS/);
  assert.match(rescindApi, /parent\.status <> 'rescinded'/);
  assert.match(rescindApi, /guest_id = NULL/);
  assert.match(rescindApi, /status = 'cancelled'/);
  assert.match(orderApi, /allocated_event/);
  assert.match(orderApi, /debited_guest/);
  assert.match(orderApi, /next_order_number = next_order_number \+ 1/);
  assert.match(schema, /serviceMode/);
  assert.match(schema, /rsvpDeadline/);
  assert.match(schema, /mapsUrl/);
});
